#!/usr/bin/env bash
# commands to istall nginx on web server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index-debian.html

# testing nginx configurations
sudo nginx -t

sudo service nginx restart
