#!/usr/bin/env bash
#commands to istall nginx on web server

sudo apt-get update
sudo apt-get install nginx
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

#testing nginx configurations
sudo nginx -t

sudo service nginx reload
